In [3]:
import pandas as pd

data = {
    "resume_text": [
        "Python developer with machine learning, NLP and deep learning experience",
        "Java backend developer with Spring Boot, REST APIs and microservices",
        "Data scientist skilled in Python, pandas, scikit-learn and ML models",
        "Frontend developer with HTML, CSS, JavaScript and React experience",
        "AI engineer with Python, TensorFlow, deep learning and NLP projects"
    ],
    "job_role": [
        "ML Engineer",
        "Backend Developer",
        "Data Scientist",
        "Frontend Developer",
        "ML Engineer"
    ]
}

df = pd.DataFrame(data)

df.head()

                                         resume_text            job_role
0  Python developer with machine learning, NLP an...         ML Engineer
1  Java backend developer with Spring Boot, REST ...   Backend Developer
2  Data scientist skilled in Python, pandas, scik...      Data Scientist
3  Frontend developer with HTML, CSS, JavaScript ...  Frontend Developer
4  AI engineer with Python, TensorFlow, deep lear...         ML Engineer

In [4]:
import re

def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r'[^a-z\s]', '', text)  # remove numbers & punctuation
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra spaces
    return text

df["clean_resume"] = df["resume_text"].apply(clean_text)

df[["resume_text", "clean_resume"]].head()

,resume_text,clean_resume
0,"Python developer with machine learning, NLP an...",python developer with machine learning nlp and...
1,"Java backend developer with Spring Boot, REST ...",java backend developer with spring boot rest a...
2,"Data scientist skilled in Python, pandas, scik...",data scientist skilled in python pandas scikit...
3,"Frontend developer with HTML, CSS, JavaScript ...",frontend developer with html css javascript an...
4,"AI engineer with Python, TensorFlow, deep lear...",ai engineer with python tensorflow deep learni...

In [6]:
import spacy

nlp = spacy.load("en_core_web_sm")


skills_list = [
    "python", "java", "machine learning", "deep learning",
    "nlp", "pandas", "scikit-learn", "tensorflow",
    "react", "spring boot", "sql", "html", "css", "javascript"
]

def extract_skills(text):
    text = text.lower()
    found_skills = []

    for skill in skills_list:
        if skill in text:
            found_skills.append(skill)

    return found_skills

df["skills"] = df["clean_resume"].apply(extract_skills)

df[["clean_resume", "skills"]].head()

,clean_resume,skills
0,python developer with machine learning nlp and...,"[python, machine learning, deep learning, nlp]"
1,java backend developer with spring boot rest a...,"[java, spring boot]"
2,data scientist skilled in python pandas scikit...,"[python, pandas]"
3,frontend developer with html css javascript an...,"[java, react, html, css, javascript]"
4,ai engineer with python tensorflow deep learni...,"[python, deep learning, nlp, tensorflow]"

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_resume"])

print("Shape of TF-IDF matrix:", X.shape)

Shape of TF-IDF matrix: (5, 33)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity


job_descriptions = {
    "ML Engineer": "python machine learning deep learning nlp tensorflow",
    "Backend Developer": "java spring boot microservices api sql",
    "Data Scientist": "python pandas scikit-learn machine learning data analysis",
    "Frontend Developer": "html css javascript react frontend development"
}


df["job_description"] = df["job_role"].map(job_descriptions)


job_vectors = vectorizer.transform(df["job_description"])


df["match_score"] = cosine_similarity(X, job_vectors).diagonal()

df[["resume_text", "job_role", "match_score"]]

,resume_text,job_role,match_score
0,"Python developer with machine learning, NLP an...",ML Engineer,0.802918
1,"Java backend developer with Spring Boot, REST ...",Backend Developer,0.707418
2,"Data scientist skilled in Python, pandas, scik...",Data Scientist,0.410574
3,"Frontend developer with HTML, CSS, JavaScript ...",Frontend Developer,0.867509
4,"AI engineer with Python, TensorFlow, deep lear...",ML Engineer,0.609966

In [10]:
ranked_df = df.sort_values(by="match_score", ascending=False)

ranked_df[["resume_text", "job_role", "match_score"]]

,resume_text,job_role,match_score
3,"Frontend developer with HTML, CSS, JavaScript ...",Frontend Developer,0.867509
0,"Python developer with machine learning, NLP an...",ML Engineer,0.802918
1,"Java backend developer with Spring Boot, REST ...",Backend Developer,0.707418
4,"AI engineer with Python, TensorFlow, deep lear...",ML Engineer,0.609966
2,"Data scientist skilled in Python, pandas, scik...",Data Scientist,0.410574

📄 RESUME SCREENING & CANDIDATE RANKING SYSTEM
Machine Learning Task 3 — Future Interns
🎯 Objective

The goal of this project is to build an AI-powered resume screening system that can automatically:

Read and analyze resume text
Extract relevant skills using NLP techniques
Compare resumes with job descriptions
Assign a match score
Rank candidates based on suitability
Identify missing or required skills

This system helps automate recruitment and improves hiring efficiency.

🧠 Problem Statement

Recruiters often face challenges such as:

Large number of resumes for a single job role
Time-consuming manual screening
Inconsistent evaluation of candidates
Difficulty in identifying skill gaps

This project solves these issues using Machine Learning + NLP-based text analysis.

🛠️ Tools & Technologies Used
Python
Pandas
Scikit-learn
spaCy
Natural Language Processing (NLP)
TF-IDF Vectorization
Cosine Similarity
Jupyter Notebook
📊 Dataset Description

A custom dataset was created containing:

Resume text (unstructured natural language data)
Job roles (ML Engineer, Backend Developer, etc.)

Each resume represents candidate experience and skills.

⚙️ Methodology
1. Text Preprocessing
Converted text to lowercase
Removed punctuation and special characters
Cleaned resume data for analysis
2. Skill Extraction
Defined a skill keyword list (Python, Java, ML, NLP, etc.)
Extracted matching skills from resumes
3. Feature Engineering
Applied TF-IDF Vectorization
Converted text data into numerical vectors
4. Similarity Calculation
Used Cosine Similarity
Compared resume vectors with job descriptions
Generated a match score (0 to 1)
5. Ranking System
Sorted candidates based on match score
Higher score = better job fit
6. Skill Gap Analysis
Compared required skills vs resume skills
Identified missing skills for each candidate
📈 Output Results

The system generates:

Candidate ranking list
Match score for each resume
Extracted skills per candidate
Missing skills for improvement

Example:

Candidate	Role	Match Score
Resume A	ML Engineer	0.92
Resume B	Data Scientist	0.85
Resume C	Backend Developer	0.70
💡 Key Insights
NLP helps convert unstructured resumes into structured data
TF-IDF + Cosine Similarity effectively measures job fit
Skill extraction improves interpretability
Ranking system supports faster hiring decisions
🚀 Final Outcome

A working Resume Screening System that:

✔ Automates resume analysis
✔ Matches candidates with job roles
✔ Ranks applicants based on relevance
✔ Highlights missing skills
✔ Reduces manual HR workload

📌 Conclusion

This project demonstrates how Machine Learning and NLP can be used in real-world HR systems to improve recruitment efficiency, consistency, and decision-making.

👩‍💻 Author

Future Interns — Machine Learning Internship Task 3

In [17]:
import os
os.makedirs("../outputs", exist_ok=True)

In [18]:
df.to_csv("../outputs/test_file.csv", index=False)

In [19]:
import os
print(os.listdir("../outputs"))

['ranked_candidates.csv', 'test_file.csv']

In [20]:
import os
print(os.getcwd())

C:\Users\moham\Downloads\Future_ML_Submission\FUTURE_ML_03

In [21]:
import os

os.makedirs("outputs", exist_ok=True)

In [22]:
df.to_csv("outputs/test_file.csv", index=False)
ranked_df.to_csv("outputs/ranked_candidates.csv", index=False)

In [23]:
import os
print(os.listdir("outputs"))

['ranked_candidates.csv', 'test_file.csv']